Feature/matsumoto yuikei
BeerShigachi/VIT_Training_Repository pull request #11
Opened 2023-07-12 04:54 UTC by YuikeiMatsumoto

Please check my branch.

2023-07-12 06:58 UTC, BeerShigachi requested changes
Please remove irrelevant files. The change does not meet the requirements.

2023-07-12 06:59 UTC, BeerShigachi requested changes

2023-07-12 06:59 UTC, BeerShigachi commented on README.md
Do not include this file.

2023-07-12 06:59 UTC, BeerShigachi commented on ayato.txt
Do not include this file.

2023-07-12 06:59 UTC, BeerShigachi commented on dummy.txt
Do not include this file.

2023-07-12 06:59 UTC, BeerShigachi commented on lam.txt
Do not include this file.

2023-07-12 06:59 UTC, BeerShigachi commented on riku.txt
Do not include this file.

2023-07-12 06:59 UTC, BeerShigachi commented on ryuta.txt
Do not include this file.

2023-07-12 06:59 UTC, BeerShigachi commented on sample.txt
Do not include this file.

2023-07-12 08:46 UTC, YuikeiMatsumoto commented
I've corrected my branch. Please check it again.

2023-07-13 01:59 UTC, BeerShigachi requested changes
Do not delete README.md

2023-07-13 02:49 UTC, YuikeiMatsumoto commented
I've resolved the conflict of my branch. Please check it.

2023-07-13 05:11 UTC, closed without merging